select
	smn_automotriz.smn_diagnostico_det_estruc_item.*
from
	smn_automotriz.smn_diagnostico_det_estruc_item,
	smn_automotriz.smn_diagnostico_det_auto
where
		smn_automotriz.smn_diagnostico_det_estruc_item.smn_diagnostico_det_auto_id=smn_automotriz.smn_diagnostico_det_auto.smn_diagnostico_det_auto_id and
		smn_automotriz.smn_diagnostico_det_auto.smn_diagnostico_det_auto_id=${fld:id}
