INSERT INTO smn_automotriz.smn_diagnostico_det_estruc_item
(
	smn_diagnostico_det_estruc_item_id,
	smn_diagnostico_det_auto_id,
	smn_componentes_rf,
	smn_item_rf,
	smn_servicios_rf,
	dde_cantidad,
	smn_tipo_componente,
	smn_forma_calculo_rf,
	smn_visible_rf,
	cmp_porcentaje,
	smn_grupo_prestador_rf,
	smn_nivel_estructura_rf
)
VALUES
(
	${seq:currval@smn_automotriz.seq_smn_diagnostico_det_estruc_item},
	${fld:smn_diagnostico_det_auto_id},
	${fld:smn_componentes_rf},
	${fld:smn_item_rf},
	${fld:smn_servicio_rf},
	${fld:dde_cantidad},
	${fld:smn_tipo_componente},
	${fld:smn_forma_calculo_rf},
	${fld:smn_visible_rf},
    ${fld:cmp_porcentaje},
	${fld:smn_grupo_prestador_rf},
	${fld:smn_nivel_estructura_rf}
)
