select
		smn_automotriz.smn_tipo_documento_afiliado.smn_tipo_documento_afiliado_id,
	smn_automotriz.smn_tipo_documento_afiliado.tdo_codigo,
	smn_automotriz.smn_tipo_documento_afiliado.tdo_descripcion,
	smn_automotriz.smn_tipo_documento_afiliado.tdo_idioma,
	smn_automotriz.smn_tipo_documento_afiliado.tdo_usuario,
	smn_automotriz.smn_tipo_documento_afiliado.tdo_fecha_registro,
	smn_automotriz.smn_tipo_documento_afiliado.tdo_hora
	
from
	smn_automotriz.smn_tipo_documento_afiliado
