select
		smn_automotriz.smn_diagnostico_det_estruc_item.smn_diagnostico_det_auto_id,
	smn_automotriz.smn_diagnostico_det_estruc_item.smn_componentes_rf
from
	smn_automotriz.smn_diagnostico_det_estruc_item 
where
	smn_automotriz.smn_diagnostico_det_estruc_item.smn_diagnostico_det_estruc_item_id = ${fld:id}
