INSERT INTO smn_automotriz.smn_contratante
(
	smn_contratante_id,
	smn_documento_id,
	cnt_numero_control,
	smn_clase_auxiliar_rf,
	smn_auxiliar_rf,
	smn_plan_id,
	cnt_fecha_de_inicio,
	cnt_cantidad_citas,
	cnt_idioma,
	cnt_usuario_id,
	cnt_fecha_registro,
	cnt_hora
)
VALUES
(
	${seq:currval@smn_automotriz.seq_smn_contratante},
	${fld:smn_documento_id},
	${seq:currval@smn_automotriz.seq_numero_control},
	${fld:smn_clase_auxiliar_rf},
	${fld:smn_auxiliar_rf},
	${fld:smn_plan_id},
	${fld:cnt_fecha_de_inicio},
	${fld:cnt_cantidad_citas},
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}'
);

INSERT INTO smn_comercial.smn_cliente
(
	smn_cliente_id,
	smn_clasificacion_cliente_id,
	smn_clase_auxiliar_rf,
	smn_auxiliar_rf,
	smn_sector_economico_rf,
	cli_nacional_ext,
	cli_vigencia,
	cli_estatus,
	cli_idioma,
	cli_usuario,
	cli_fecha_registro,
	cli_hora
)
VALUES
(
	${seq:currval@smn_comercial.seq_smn_cliente},
	2,
	${fld:smn_clase_auxiliar_rf},
	${fld:smn_auxiliar_rf},
	2,
	'N',
	${fld:cnt_fecha_de_inicio},
	'AC',
	'${def:locale}',
	'${def:user}',
	'${def:date}',
	'${def:time}'
)

