select
		smn_automotriz.smn_campos_visualizacion_monitores_dispositivos.smn_campos_vis_mon_dis_id,
	smn_automotriz.smn_campos_visualizacion_monitores_dispositivos.smn_dispositivos_id,
	smn_automotriz.smn_campos_visualizacion_monitores_dispositivos.smn_series_id,
	smn_automotriz.smn_campos_visualizacion_monitores_dispositivos.cvm_datos_pac,
	smn_automotriz.smn_campos_visualizacion_monitores_dispositivos.cvm_unidad_llamada,
	smn_automotriz.smn_campos_visualizacion_monitores_dispositivos.cvm_pacientes_espera,
	smn_automotriz.smn_campos_visualizacion_monitores_dispositivos.cvm_tiempo_aprox_espera,
	smn_automotriz.smn_campos_visualizacion_monitores_dispositivos.cvm_fecha_registro
from
	smn_automotriz.smn_campos_visualizacion_monitores_dispositivos 
where
	smn_automotriz.smn_campos_visualizacion_monitores_dispositivos.smn_campos_visualizacion_monitores_dispositivos_id = ${fld:id}
