select
		smn_automotriz.smn_presupuesto_detalle.smn_presupuesto_id,
	smn_automotriz.smn_presupuesto_detalle.smn_servicios_rf,
	smn_automotriz.smn_presupuesto_detalle.prd_cantidad,
	smn_automotriz.smn_presupuesto_detalle.prd_precio,
	smn_automotriz.smn_presupuesto_detalle.smn_moneda_rf,
	smn_automotriz.smn_presupuesto_detalle.prd_precio_ma,
	smn_automotriz.smn_presupuesto_detalle.prd_monto_moneda_local,
	smn_automotriz.smn_presupuesto_detalle.prd_moneda_alterna,
	smn_automotriz.smn_presupuesto_detalle.prd_fecha_registro
from
	smn_automotriz.smn_presupuesto_detalle 
where
	smn_automotriz.smn_presupuesto_detalle.smn_presupuesto_detalle_id = ${fld:id}
